### ISSUE TITLE
Parameter documentation for function has disappeared

### ISSUE THREAD

**Issue by X-Ryl669** [matusnovak/doxybook2#10]
If you look into `AudioBuffer.hpp` source, for the method `play` there is:
```
/*!
             * @brief Play this buffer
             * @param manager Which manager to play the sound with
             * @throw Exception If this buffer is already playing
             */
            void play(AudioManager& manager) const;
```
Doxygen create a example with the parameter `manager` which is documented. Yet, it's not in the generated markdown files (nor is the `throw` information).

**Comment by matusnovak** [comment]
Hi @X-Ryl669 

I have accidentally introduced this issue. At some point I have renamed the `paramList` in the default templates by a mistake and it was no longer rendered. 

I have fixed it in the new release [releases/tag/v1.1.0](https://github.com/matusnovak/doxybook2/releases/tag/v1.1.0).

Example screenshot from [here](https://matusnovak.github.io/doxybook2/hugo-learn/classes/classengine_1_1audio_1_1audiobuffer/):

![image](https://user-images.githubusercontent.com/10331278/80246453-b76a2c00-866c-11ea-955b-22263c29833a.png)

Generated from the following source:

```cpp
/*!
 * @brief Play this buffer
 * @param manager Which manager to play the sound with
 * @throw Exception If this buffer is already playing
 */
void play(AudioManager& manager) const;
```
