### ISSUE TITLE
Doxybook is missing a --version command line argument 

### ISSUE THREAD

**Issue by X-Ryl669** [matusnovak/doxybook2#12]
Hi,

 It would be very useful if doxybook had a `--version` command line argument so we can know if it's updated upstream.

Thanks

**Comment by matusnovak** [comment]
Hi @X-Ryl669 

Thanks for the suggestion. I have added `--version` (and a short version of that as `-v`) to the command line. It uses `git describe` during CMake configuration step so it automatically follows the git tags.

It has been added to the 1.1.4 release here: [releases/tag/v1.1.4](https://github.com/matusnovak/doxybook2/releases/tag/v1.1.4)
