### ISSUE TITLE
Generating templates?

### ISSUE THREAD

**Issue by blue-santa** [matusnovak/doxybook2#2]
I'm following the instructions to generate templates and am receiving the following errors.

```
$ doxybook2 --generate-templates ./templates
no option arguments to convert
```

Any tips? Something I misread? Thanks!

**Comment by blue-santa** [comment]
After some googling, this looks like an error coming from the `argagg` lib, which I assume is the command line parser... So, perhaps there's some format for submitting the path and I've misunderstood how to submit it.

**Comment by matusnovak** [comment]
hi @siddhartha-crypto 

Yes, there was a "small" typo when processing the arguments. My bad. It should be fixed now in **v1.0.1** https://github.com/matusnovak/doxybook2/releases/tag/v1.0.1

Let me know if that solves your problem.

**Edit:**

You were using it properly. The `$ doxybook2 --generate-templates ./templates` is the correct way to generate templates.

**Comment by blue-santa** [comment]
Awesome. I was able to generate the templates now. Taking a look through how these work.

Nice job on all of this! Very thorough.

are you active in any online chat communities?

**Comment by blue-santa** [comment]
Also, is there any additional information on the templates?

I played around with them today just a little, but without understanding the xml behind them, adjusting them is challenging.

**Comment by matusnovak** [comment]
@siddhartha-crypto 

I am not active in any online chat community that's related to open source projects. But I do have WhatsApp, Hangouts, and Discord. Also you can contact me on my email email@matusnovak.com .

> Also, is there any additional information on the templates?

Not at the moment. I should update the readme with more details and with examples. However, what things are you adjusting in the templates and needs more clarification?

> adjusting them is challenging

Yes, it was challenging to write them in the first place. The template engine [Inja](https://github.com/pantor/inja.git) (which is based on Python's Jinja2) has a strict syntax and does not play nice with extra whitespace (also no comment support), making the templates hard to read.

**Comment by blue-santa** [comment]
Gotcha. I'll shoot you an email. We should connect on Discord.
