### ISSUE TITLE
C# Properties throwing errors

### ISSUE THREAD

**Issue by AdamFrisby** [matusnovak/doxybook2#20]
Hi there - 

I've got a bunch of logs in our build complaining about 

Warning at Doxygen.cpp:72 Failed to parse member className error: Exception at Enums.cpp:30 Kind property not recognised please contact the author

This appears to be caused by C# properties (a kind of hybrid method/field; syntactically a field, but executes as a get/set method) - I have attached some sample XMLs you can use to reproduce the issue.

Thanks!

**Comment by matusnovak** [comment]
Hi @AdamFrisby 

I have added both `event` and `property`. It's on the `refactor-default-templates-events-props` branch. You can find a pre-built binary here: (see the artifacts) https://github.com/matusnovak/doxybook2/actions/runs/377524381

Additionally, I have run your sample xml files with the `mkdocs-material` example, here is the output: 
[mkdocs-material.zip](https://github.com/matusnovak/doxybook2/files/5579858/mkdocs-material.zip)

I have never run Doxygen with a C# project, so I am not sure how the output should look like. I hope I got the properties and events right. 

Let me know if this solves your issue.

**Comment by AdamFrisby** [comment]
That is awesome, thankyou!

**Comment by matusnovak** [comment]
Merged to master and released in [releases/tag/v1.3.0](https://github.com/matusnovak/doxybook2/releases/tag/v1.3.0)
