### ISSUE TITLE
MathJax Compatibility

### ISSUE THREAD

**Issue by amirmasoudabdol** [matusnovak/doxybook2#30]
I've noticed that doxybook doesn't really render Doxygen TeX equations properly. So, I was wondering if it's possible to have an option for handling this.

The issue is that Doxygen has its [own syntax](https://www.doxygen.nl/manual/formulas.html) for formula and they are not being translated to something Markdown friendly. But, I think it should be pretty straightforward to slightly change the formula and provide something that MathJax understand. I believe this is what Doxygen does under the hood to generate it's HTML files.

For instance, a Doxygen formulate like `\f$\beta\f$` will be translated into this XML entry, `<formula id="4">$ \beta $</formula>` and be rendered into this `\( \beta \)` in the HTML file, and then MathJax can just render this with no problem.

P.S. I'm slowly starting to look into to your code, so, maybe if I find some time, I can make a PR for one of these issues/features! 😊

**Comment by matusnovak** [comment]
I'll get on it. Sounds like a good feature.

> P.S. I'm slowly starting to look into to your code

Try not to :D At least for now. I am currently  working on refactoring it (including adding whitespace fix into templates) and it will take some time to do. Will be much more readable afterwards.

**Comment by matusnovak** [comment]
Should be working now.

See the precompiled binary in the generated artifacts from here: https://github.com/matusnovak/doxybook2/actions/runs/480997354

So, when you type an inline formula as `\f$\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}\f$` or a block formula as `\f[ ... \f]` it will be converted into `\(\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}\)` and `\[ ... \]` respectively.

You can change the prefix and suffix of `\( ... \)` `\[ ... \]` using the config. By default it is `\( ...\)` for inline formulas and `\[ ... \]` for block formulas. Check out the config properties `formulaInlineStart` in the readme here: https://github.com/matusnovak/doxybook2#Config-values

I have added an example which can be viewed in the mkdocs-readthedocs example [here](https://matusnovak.github.io/doxybook2/mkdocs-readthedocs/).

![2021-01-12 19_57_50-Doxybook2 Example — Firefox Developer Edition](https://user-images.githubusercontent.com/10331278/104363956-36aed100-5516-11eb-9787-3a9797c27049.png)

I will tag-release it together with some other things later.

**Comment by amirmasoudabdol** [comment]
That’s great! Thanks again! 🙏🏼

**Comment by matusnovak** [comment]
Done, released here: https://github.com/matusnovak/doxybook2/releases/tag/v1.3.3
