### ISSUE TITLE
docsify template ?

### ISSUE THREAD

**Issue by X-Ryl669** [matusnovak/doxybook2#4]
In the genuine doxybook, there was a docsify output. Do you have some equivalent in doxybook2 ?

**Comment by matusnovak** [comment]
Hi @X-Ryl669 

There wasn't a Docsify template but I have added it just now. You can find the example files in here: [tree/master/example/docsify](https://github.com/matusnovak/doxybook2/tree/master/example/docsify). 

The only special thing about Docsify is that it does not support YAML Front Matter [citation needed]. Doxybook2 creates it by default, but you can disable it simply by providing a template folder with a single **empty** file called `header.tmpl`. To use the templates, simply add `--templates example/docsify/.doxybook/templates` to the command line. You can find this in the Docsify example folder.

A sample screenshot:

![screenshot_docsify_default](https://user-images.githubusercontent.com/10331278/78280666-bf292b80-7519-11ea-9179-80194bbfbdc5.jpg)

**Comment by X-Ryl669** [comment]
Thanks!
