### ISSUE TITLE
 Failed to create directory

### ISSUE THREAD

**Issue by lishali-fm** [matusnovak/doxybook2#40]
When I run: doxybook2 --output md --input /xml, got this error: Exception at Utils.cpp:155 Failed to create directory md\Classes error 3.

**Comment by matusnovak** [comment]
It would most likely fail if Doxybook does not have permission to create that directory. 

Also, if you create it yourself, it will skip creating the directory, and should proceed without a problem.

**Comment by lishali-fm** [comment]
I manually created the directory and it worked. Thanks!

**Comment by Germwalker** [comment]
Hello, i have the same problem with the latest release (1.4.0) on windows and linux. 

An error is thrown while creating the generated files folder : 
```bash
[error] Exception at Utils.cpp:218 Failed to create directory markdown/Classes error -1 
```
If i manualy create the directory i have this error :
```bash
[error] Exception at Renderer.cpp:356 Failed to open file for writing markdown/Namespaces/d8/dcc/namespacestd.md
```
The command i used to generate was : 
```bash
./doxybook2 --input ../xml --output markdown
```
Same error at the same place on windows and linux. The folder tree is created nicely but any file is present is the tree : 
```bash
[root@fedora markdown]# ll
total 0
drwxr-xr-x. 1 root root 0 17 juin  10:22 Classes
drwxr-xr-x. 1 root root 0 17 juin  10:22 Examples
drwxr-xr-x. 1 root root 0 17 juin  10:22 Files
drwxr-xr-x. 1 root root 0 17 juin  10:22 images
drwxr-xr-x. 1 root root 0 17 juin  10:22 Modules
drwxr-xr-x. 1 root root 0 17 juin  10:22 Namespaces
drwxr-xr-x. 1 root root 0 17 juin  10:22 Pages
[root@fedora markdown]# du -hs
0	.

```
I cannot provide the XML stuff or maybe on demand, sensitive stuff inside. 
I tried with the previous version without any luck. 
Also tried to execute the program as admin on windows and root on linux, nothing's working.
