### ISSUE TITLE
Documentation mentions examples.bat but I cant find it in the repository?

### ISSUE THREAD

**Issue by petebannister** [matusnovak/doxybook2#41]

**Comment by matusnovak** [comment]
Hi @petebannister 

Sorry about that. I should remove that from the docs. The file was essentially a shorter version of this: https://github.com/matusnovak/doxybook2/blob/master/.github/workflows/build.yml#L251-L330 Nothing special, just a predefined set of inputs/outputs command line arguments to run doxybook2 with the examples.
