### ISSUE TITLE
Exception at Doxygen.cpp:209 No <compound> element in file docs/doxygen/xml/index.xml

### ISSUE THREAD

**Issue by JoshMarler** [matusnovak/doxybook2#60]
Hey folks, 

I'm hitting the following error when attempting to generate markdown from my doxygen xml:

```
Exception at Doxygen.cpp:209 No <compound> element in file docs/doxygen/xml/index.xml
```

Any thoughts on how I can troubleshoot this or what the likely cause is?

We're using the following comment style:

```
/// 
/// Some text
///
```

**Comment by matusnovak** [comment]
Hi @JoshMarler 

Sorry for a late reply. Could you send me the xml files? Mainly the contents of the docs/doxygen/xml/index.xml

It seems Doxygen did not generate the contents correctly or the xml file is in an unexpected format.

**Comment by CharlesSamson** [comment]
I ran into the same problem. It was due to a generated doxygen that has no doc, i.e. the `index.xml` does not contain any `<compound>` tag:

```xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygenindex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd" version="1.9.2" xml:lang="en-US">
</doxygenindex>
```

A more helpful error message would be welcome.

**Comment by matusnovak** [comment]
Hi. I am sorry but I have decided to archive this repository. More details in the repo readme.
