### ISSUE TITLE
safeAnchorId does not replace underscore with hyphen 

### ISSUE THREAD

**Issue by SeFlossf** [matusnovak/doxybook2#63]
The safeAnchorId function should also replace '_' with '-'.
Otherwise the generated links to e.g. snake-case function names don't work later on

**Comment by matusnovak** [comment]
Thank you for noticing this. I will get on it.

**Comment by matusnovak** [comment]
Fixed in https://github.com/matusnovak/doxybook2/releases/tag/v1.4.0
