### ISSUE TITLE
Support graphviz in doxygen docs

### ISSUE THREAD

**Issue by bhaveshvasandani** [matusnovak/doxybook2#67]
I have been using graphviz to generate some graphs to document workflows along with doxygen. It would be nice to get markdowns rendered with those graphs. https://www.doxygen.nl/manual/diagrams.html

`Warning at XmlTextParser.cpp:69 Text tag "dot" not recognised, please contact the author
`

**Comment by matusnovak** [comment]
Hi @bhaveshvasandani 

Thank you for the suggestion. Indeed, it would be nice to have. I will get on it, but I am currently busy with other life-related tasks, and may take some time for me to do it.

**Comment by kammce** [comment]
+1 this

**Comment by winterz** [comment]
this would be a really nice improvement for us.

**Comment by matusnovak** [comment]
Hi. I am sorry but I have decided to archive this repository. More details in the repo readme.
