### ISSUE TITLE
Header source still displayed even when SOURCE_BROWSER = NO

### ISSUE THREAD

**Issue by billcxx** [matusnovak/doxybook2#74]
For doxygen generated html, the "Go to the source code of this file" link won't appear when I set 
```
SOURCE_BROWSER = NO
VERBATIM_HEADERS = NO
INLINE_SOURCES = NO
```
but doxybook2 still captures the programlisting part of the xml and create a source code section for each of the Files. 

Is there any way to suppress doxybook2 from transferring the source code to the final markdown file?

**Comment by matusnovak** [comment]
Hi @billcxx 

There is currently no way to disable that. I will add this feature in.

**Comment by matusnovak** [comment]
Hi. I am sorry but I have decided to archive this repository. More details in the repo readme.
