### ISSUE TITLE
Cannot build on Mac OS

### ISSUE THREAD

**Issue by Babilinski** [matusnovak/doxybook2#75]
Following the instructions [here](https://github.com/microsoft/vcpkg#quick-start-unix) and I was not able to build it on my device:
```
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/Xcode
```

**Comment by matusnovak** [comment]
Hi @Babilinski 

I do not own a Mac. I have only tested this project through GitHub actions and a shady VM that was running a slightly outdated version of OSX. What I can tell you is that this project is not doing anything special with Mac OS libraries. The `-lSystem` library is definitely coming from the linker (as in, added by linker itself) and not from this project.

I have found a similar issue here that may help you: https://github.com/ponylang/ponyc/issues/3684

This project compiles just fine on GitHub actions with Mac OSX runner with  Mac OS X 10.15.7 (19H1417) and AppleClang 12.0.0.12000032. You can see this last build of 1.4.0 for Mac OS here: https://github.com/matusnovak/doxybook2/runs/3646834909?check_suite_focus=true

Either something weird has changed in the latest Mac OS update that may cause `-lSystem` to be gone or I am missing something very obvious.

**Comment by matusnovak** [comment]
Hi. I am sorry but I have decided to archive this repository. More details in the repo readme.
