### ISSUE TITLE
Citation is plain text not hyperlink

### ISSUE THREAD

**Issue by billcxx** [matusnovak/doxybook2#77]
I'm using @cite to create a citation in my documentation. Doxybook2 renders it as plain text "[[1]]" and a *citelist.md* file for the bibliography list.

Is there a way to render the citing number as a hyperlink pointing to the reference rather than plain text?

If no, it would be a nice feature to have a hyperlink from the citing number to the reference in the *citelist.md*, as it is in the doxygen html and latex.

**Comment by matusnovak** [comment]
Hi @billcxx 

Citations are not correctly handled by Doxybook2 at the moment. This is definitely something that I will add in. However, it may take a while for me to get to this.

**Comment by matusnovak** [comment]
Hi. I am sorry but I have decided to archive this repository. More details in the repo readme.
