### ISSUE TITLE
\ref of the sections on the same page does not render correctly 

### ISSUE THREAD

**Issue by billcxx** [matusnovak/doxybook2#78]
Here is an example doxygen page
```
/**
@page faq Frequently Asked Questions

@section faq_interface Interface
1. @ref faq_interface_q1 

@subsection faq_interface_q1 One question.
The answer to this question

*/
```

The doxybook2 rendered result of the ref link to the subsection is as follows
```
1. [One question]
```

Expected render result is as follows (need to remove punctuation, use lower case, and replace space with hyphen)
```
1. [One question](#one-question)
```

**Comment by matusnovak** [comment]
Hi. I am sorry but I have decided to archive this repository. More details in the repo readme.
