### ISSUE TITLE
Deprecated Functions

### ISSUE THREAD

**Issue by victorgram** [matusnovak/doxybook2#8]
When generating the documentation for each function of a class, the information detailing whether a function is deprecated is missing. 
The information cannot be found anywhere in the *.md.json file for the class.

**Comment by matusnovak** [comment]
Hi @victorgram 

The deprecation has not been implemented... yet.

Just to be clear, are we talking about the [\deprecated](http://www.doxygen.nl/manual/commands.html#cmddeprecated) command? I will add that in.

How would you like it to appear on the markdown output?

**Comment by victorgram** [comment]
Hi @matusnovak 
Thanks for the very quick reply, and yes I am referencing the \deprecated command that can be added to a function.

I don't really mind how the markdown will look, since I already use the .tmpl files to customize the look.

**Comment by matusnovak** [comment]
@victorgram 

Done, released as [releases/tag/v1.0.7](https://github.com/matusnovak/doxybook2/releases/tag/v1.0.7)

If the function/class/etc is documented via `@deprecated <text>` it will appear in the output JSON as `"deprecated": "<text>"`.  If the function/class/etc is not deprecated, the key-value is not in the JSON output. So, if using custom templates, the syntax should be `{% if exists("deprecated") %}{{deprecated}}{% endif %}`.

Additionally, it is added to the default templates and it will appear in the detailed section. Example screenshot:

![image](https://user-images.githubusercontent.com/10331278/79912232-fce6e900-8421-11ea-99a3-91e3834b9218.png)

**Comment by victorgram** [comment]
Wow! You're quick!
Thank you so much for that! :)
