### ISSUE TITLE
Feature Request: Relative Link support

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [matusnovak/doxybook2#80]
Hi, first up thanks for your tool, it is working well so far :)

One of the few problems we have encountered though is that providing a hard-coded `baseUrl` is required.

This is a problem, as we want to organize our documentation website by version, so a link would look something like this: `docs.company.com/<project>/<version>/`.
with a `latest` symlink linking to the latest version folder.

Because the baseUrl needs to be hard-coded, we need a mechanism in our build system to adapt the baseUrl for every version, or do it manually. Which is quite suboptimal.

Ideally we'd want doxybook2 to generate relative links for every page, so that it doesn't matter where the docs are located.

If you give me a brief overview of how you'd like such a feature implemented (relevant classes, how to pass the data to where it's needed, etc.) I can possibly get time from my company to implement this feature myself and create a PR.

Kind Regards,
Leon

**Comment by Reen** [comment]
If you leave the baseUrl empty, links will be generated relative to the output directory. Then, you just need a static site generator that can handle this properly. I was just tooling around with MkDocs, which unfortunately can't. But, you can set doxybook2's `useFolders` to `false`. Then everything ends up in one folder, and relative linking works as expected.

**Comment by LeonMatthesKDAB** [comment]
I'm trying this out right now.
The problem currently seems to be the Classes.md file that lists all Classes, and all other listing files.
They are accessed under the `Classes/` Url. This file then links to i.e. `classKDBindings_1_1Binding` which tries to open `Classes/classKDBindings_1_1Binding`, which of course doesn't exist, because it needs to be `classKDBindings_1_1Binding`.

Maybe I can get mkdocs to a different behavior. But I think that's the reason I had to set a `baseUrl` in the first place.

**Comment by Reen** [comment]
Have you tried running doxybook with `doxybook2 ... --config-data '{"useFolders": false}'`? Try clearing your output folder first. For me this results in a completely flat output of markdown files.

**Comment by LeonMatthesKDAB** [comment]
The output is indeed completely flat.

The problem is a mix of the links doxybook2 generates, as well as the way they are handled by mkdocs.

In the `Classes.md` file, doxybook2 generates a link to the namespace page like this:
`**namespace [KDBindings](namespaceKDBindings/)**`
Where the link to the page of the classes file is `https://localhost:8000/kdbindings/1.0.0/Classes/`.
When I now click on that link, it appends it to the current link and tries to access the address `https://localhost:8000/kdbindings/1.0.0/Classes/namespaceKDBindings`. Which of course doesn't exist...

If I manually change the link to a markdown format, it works:
`**namespace [KDBindings](namespaceKDBindings.md)**`
Because then we're not generating links that behave like folders (`Classes/`,`namespaceKDBindings/`), but rather to the files directly, which mkdocs can translate into the correct folder-like links.

**Comment by LeonMatthesKDAB** [comment]
Is there an option somewhere in mkdocs to translate the link output format to link to the .md files?

**Comment by LeonMatthesKDAB** [comment]
Hm, setting `linkSuffix` to `".md"` seems to fix the issue :thinking: 

So my current settings are:
- `"linkSuffix": ".md"`
- `"baseUrl": ""`
- `"useFolders": false`

Which seems to work well with MkDocs.

This is very different from the recommended settings in the README.md, which suggests to set `"linkSuffix": "/"`, as well as providing a baseUrl. The documentation for `useFolders` is also missing in the Readme file, so maybe that should be updated.

**Comment by matusnovak** [comment]
Hi. I am sorry but I have decided to archive this repository. More details in the repo readme.
