### ISSUE TITLE
Example pages markdown is missing newline

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [matusnovak/doxybook2#83]
After switching from v1.3.6 to v1.4.0 the examples pages in the docs for our library are no longer rendering correctly.

There seems to be a newline missing after the end of the example documentation and the beginning of the code block that displays the example file content.

### Expected output:
![image](https://user-images.githubusercontent.com/84974957/142204066-7f7d8816-715e-45cd-b558-93d0528b3a36.png)

### Actual output:
![image](https://user-images.githubusercontent.com/84974957/142204001-f6c1da35-66ca-4f9e-a62f-da0d5cdc01c8.png)

### Cause of the issue
Note the "```cpp" that should mark the beginning of the code block, that ends up visible in the HTML instead.

Markdown generated by doxybook2: https://pastebin.com/GxUWQzXR
As you can see, the "```cpp" is not on a separate line, which is what causes the issue.

The issue does not appear if the description of the example ends in a code block.

### Workaround
For now there is a workaround for this problem by adding a `<br/>` HTML tag to the end of the `@example` doxygen comment. This is of course far from ideal though.

### Further resources
The doxygen comment in our library: https://github.com/KDAB/KDBindings/blob/1.0/src/kdbindings/binding_evaluator.h#L141
And the example file: https://github.com/KDAB/KDBindings/blob/1.0/examples/06-lazy-property-bindings/main.cpp

**Comment by matusnovak** [comment]
Hi. I am sorry but I have decided to archive this repository. More details in the repo readme.
