### ISSUE TITLE
Rendering of parameter types and names needs escaping in table summaries

### ISSUE THREAD

**Issue by odracirnumira** [matusnovak/doxybook2#84]
Suppose a C function defined like so:

```
# some_header.h
int some_function(intptr _Nullable my_parameter_);
```

Note the how the sequence "`_Nullable my_parameter_`" starts and ends with an underscore.

When the above is rendered in Markdown, the following is generated:

```

---
title: some_header.h
---

# some_header.h


## Functions

|                | Name           |
| -------------- | -------------- |
| int | **[some_function](Files/some__header_8h.md#function-some-function)**(intptr _Nullable my_parameter_) |

... OTHER THINGS ...
```

As one can see, the table has the sequence "`_Nullable my_parameter_`", which ends up being rendered in italics, as can be seen in the attached picture.

![Screen Shot 2021-11-28 at 3 48 07 PM](https://user-images.githubusercontent.com/2472545/143791276-aa79ced6-4a24-4dc5-990a-90ed9aaca860.png)

The above is generated with a default Doxygen file where XML output has been enabled, and with the default templates and master version of doxybook2.

To the best of my understanding after a couple of days learning about this code base, I believe the problem is that both `<type>` and `<declname>` XML elements are not being properly escaped (`<defname>` has the same problem). More specifically, when `TextMarkdownPrinter` processes a `TEXT` node, it should escape the text if the context is adequate.

I've been playing around to see how to fix this, and here's what I've come up with. I'm not happy, since it seems excessively complicated, but hopefully this can be used as a starting point for a better approach to fix this issue:

### Solution: more node types in `XmlTextParser`

The idea here is that `TextMarkdownPrinter` needs to be smarter when dealing with `TEXT` nodes. By adding `TYPE`, `DECLNAME` and `DEFNAME` to `XmlTextParser::Node::Type`, the `TextMarkdownPrinter` will have enough context to make a smarter decision. 

`TextMarkdownPrinter::print` will now also call `Utils::escape` when processing a `TEXT` node if the `parent` node is of type `TYPE`, `DECLNAME`, or `DEFNAME`. This fixes `TEXT` occurrences that should be escaped when they are in a context where not being escaped might lead to the problem presented in this issue.

The above is not the full story though. `Doxybook2::Node::Param` cannot just have a `name` property holding the Markdown version of the parameter name. We also need a "plain" version (just like we do with, say, `typePlain`) so we can add it to places where Markdown will render text as-is, without applying any styling. Here I'm more specifically referring to code blocks (like triple quotes blocks). If we place the properly Markdown escaped version of a parameter name (or its type, for the matter) in a code block, it'll render the escaping sequence, which we don't want. In the example from the screenshot above, if we didn't add a `namePlain` field, then the prototype rendered in `function some_function` would show the following:

```cpp
int some_function(
    int *&#95;Nullable my&#95;parameter&#95;
)
```

Happy to put out a pull request with my code if that helps in understanding this problem and the solution I'm proposing.

Note that, as a thought experiment, I also thought of a solution where rather than adding more node types to `XmlTextParser` we could instead have the `TextMarkdownPrinter::print` method escape `TEXT` nodes by default. This likely comes from my lack of understanding of many parts of this codebase, but wouldn't escaping `TEXT` by default be a more reasonable default?

**Comment by matusnovak** [comment]
Hi. I am sorry but I have decided to archive this repository. More details in the repo readme.
