### ISSUE TITLE
Exception at Enums.cpp:324 Type 6 not recognised please contant the author!

### ISSUE THREAD

**Issue by capraynor** [matusnovak/doxybook2#85]
Thanks for your tool, it is excellent. 

During my generating a doc with doxybook2, we encountered an error: 
```
Exception at Enums.cpp:324 Type 6 not recognised please contant the author!
```

Running command:

```
doxybook2 --input ./xml --output ./markdown
```

![image](https://user-images.githubusercontent.com/3467515/146307798-eaa88e1e-3ddd-4f0a-af06-9118c4678376.png)

The XML files attached: 

[generated-from-java.zip](https://github.com/matusnovak/doxybook2/files/7724527/generated-from-java.zip)

 generated by : 

Doxygen 1.9.2

Could you please help to check what's going on, and are there any workarounds.

Thank you so much. 

Regards
Raynor

**Comment by danjimilk** [comment]
I have encountered the same error. Anybody knows the progress with this issue?

**Comment by matusnovak** [comment]
Hi. I am sorry but I have decided to archive this repository. More details in the repo readme.
