### ISSUE TITLE
Error while building with Hugo

### ISSUE THREAD

**Issue by Germwalker** [matusnovak/doxybook2#94]
Hello, i have an error while builiding the generated mk files with Hugo : 
```bash
Error: Error building site: "./Doc/hugo_book/content/Files/main_8h.md:3:1": 
failed to unmarshal YAML: yaml: line 2: mapping values are not allowed in this context
```
Here is the file :
[main_8h.md](https://github.com/matusnovak/doxybook2/files/8928782/main_8h.md)

Here is the XML file generated by Doxygen _(i added .txt for github)_ : 
[main_8h.xml.txt](https://github.com/matusnovak/doxybook2/files/8928786/main_8h.xml.txt)

Here is the tool log : 
[doxybook2.log.txt](https://github.com/matusnovak/doxybook2/files/8928826/doxybook2.log.txt)

Tried to build on Linux Fedora without luck ... 
I'm generating a doc for a MCU Cortex-M4, maybe some things are not trivial. 

Here is my generating script : 
```bash
# -----------------------------------------------
#   Generate Hugo-Learn website from Doxygen XML
# -----------------------------------------------

docBuilderFolder="hugo_learn"
docBuilderTheme="https://github.com/matcornic/hugo-theme-learn" 
themeCommit="51dbdcf4aaef01d02e78a6ea76b2a6fde5842b55"
docBuilderGen=$root/Doc/$docBuilderFolder

cp -r $doxybook2Folder/$docBuilderFolder $docPath/$docBuilderFolder

mkdir $docBuilderGen/content
mkdir $docBuilderGen/themes

sudo $doxybook2Bin  \
    --input $docPath/xml \
    --output $docBuilderGen/content \
    --config $docBuilderGen/.doxybook/config.json \
    --templates $docBuilderGen/.doxybook/templates

# set rights, download theme then build
sudo chmod -R 777 $docPath
git clone $docBuilderTheme $docBuilderGen/themes/hugo-theme-learn
#git checkout $themeCommit
cd $docBuilderGen && hugo && cd $root
```

I used the files found in /example to build from XML & from mk. 
Am i doing something wrong ?

**Comment by matusnovak** [comment]
Hi. I am sorry but I have decided to archive this repository. More details in the repo readme.
