### ISSUE TITLE
Using ALIASES with @par renders incorrectly to markdown

### ISSUE THREAD

**Issue by lysdexic-audio** [matusnovak/doxybook2#96]
Using ALIASES with @par renders incorrectly to markdown 

Adding this to doxyfile.bak

`ALIASES  += sideeffect="@par Side Effects:^^"`

Then generating via:

`doxybook2 --input xml ...`

### function anExampleFunction:

```objective-c
virtual void  function anExampleFunction:(
    void(^)(BOOL) completion
)
```

An example description

**Parameters**: 

  * **completion** client supplied completion handler

**Par**: Side Effects:

a side effect

**Comment by matusnovak** [comment]
Hi. I am sorry but I have decided to archive this repository. More details in the repo readme.
